market/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
	title=StringField('Title')
	content=TextAreaField('Content',validators=[DataRequired()])
	submit=SubmitField('Post')

market/main/routes.py
from flask import render_template, request, Blueprint
from market.models import Post
from flask_login import login_user, current_user, logout_user, login_required

main=Blueprint('main',__name__)


@main.route("/market")
@login_required
def market_page():
    page=request.args.get('page',1,type=int)
    items=Post.query.order_by(Post.date_posted.desc()).paginate(page=page,per_page=5)
    return render_template('market.html',items=items)


@main.route("/")
@main.route('/home')
def home():
    return render_template('home.html')

market/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from market import db
from market.models import Post
from market.posts.forms import PostForm

posts=Blueprint('posts',__name__)

@posts.route("/post/new",methods=['GET','POST'])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        flash('Your post has been create ','success')
        post=Post(title=form.title.data,content=form.content.data,author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.market_page'))


    return render_template('create_post.html',title='New Post',form=form,legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post=Post.query.get_or_404(post_id)
    return render_template('post.html',title=post.title,post=post)


@posts.route("/post/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form=PostForm()
    if form.validate_on_submit():
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Posti eshte updatuar','success')
        return redirect(url_for('posts.post',post_id=post.id))
    elif request.method=='GET':
        form.title.data=post.title
        form.content.data=post.content


    return render_template('create_post.html',title='Update Post', form=form,legend='Update Post')
    
    
#Kjo eshte thjesht sa per test per gitlabin



@posts.route("/post/<int:post_id>/delete",methods=['POST'])
@login_required
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('U fshi me sukses','success')
    return redirect(url_for('main.market_page'))

market/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from market import db, bcrypt
from market.models import User, Post
from market.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from market.users.utils import save_picture
from market import  mail
from flask_mail import Message

users=Blueprint('users',__name__)

@users.route("/register",methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_pw=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,password=hashed_pw)
        db.session.add(user)
        db.session.commit()

        flash(f'Account created ','success')
        return redirect(url_for('users.login'))

    return render_template('register.html',title='Register',form=form)


@users.route("/login",methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password,form.password.data):
            login_user(user,remember=form.remember.data)
            next_page=request.args.get('next')
         
            return  redirect(next_page) if next_page else  redirect(url_for('main.market_page'))
        else:
        	flash('login pa sukses','danger')
    return render_template('login.html',title='login',form=form)

@users.route("/logout")
def logout():
    logout_user()

    return redirect(url_for('users.login'))



def send_resend_email(user):
    token = user.get_reset_token()
    msg=Message('Password Reset Request',sender='noreply@demo.com',recipients=[user.email])
    msg.body=f'''TO reset the paswword visit the link
{url_for('users.reset_token',token=token,_external=True)}

If you did not make this request simply ignore this email.


'''
    mail.send(msg)    





@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file=save_picture(form.picture.data)
            current_user.image_file=picture_file
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('Your account has been updated','success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data=current_user.username
        form.email.data =current_user.email
    image_file=url_for('static',filename='profile_pics/'+ current_user.image_file)
    return render_template('account.html',title='Account',image_file=image_file,form=form)



@users.route("/user/<string:username>")
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    items=Post.query.filter_by(author=user)\
    .order_by(Post.date_posted.desc())\
    .paginate(page=page,per_page=5)
    return render_template('user_posts.html',items=items,user=user)



@users.route("/reset_password",methods=['GET','POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form =RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_resend_email(user)
        flash('an email has been send with instructions','info')
        return redirect(url_for('users.login'))   
    return render_template('reset_request.html',title='Reset Password',form=form)


@users.route("/reset_password/<token>",methods=['GET','POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user=User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid token or expired','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw=bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user=User(username=form.username.data,email=form.email.data,password=hashed_pw)
        user.password=hashed_pw
        db.session.commit()

        flash(f'Password has been updated ','success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html',title='Reset Password',form=form)

market/templates/account.html
{% extends "layout.html" %}
{% block content %}
  
	<div class ="content-section">
	<div class="content-section">
	  <div class="media">
	    <img class="rounded-circle account-img" src="{{image_file}}">

	    <div class="media-body">
	      <h2 class="account-heading">{{ current_user.username}}</h2>
	      <p class="text-secondary">  {{current_user.email}}  </p>
	    </div>
	  </div>
	  <!-- FORM HERE -->    <div class="content-section">
     	<form method="POST" action="" enctype="multipart/form-data">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > Account info </legend>
<div class="form-group">
	{{form.username.label(class="form-control-label")}}

	{% if form.username.errors %}
{{form.username(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.username.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.username(class="form-control form-control-lg")}}
{%endif%}

	
	
	


</div>

<div class="form-group">
	{{form.email.label(class="form-control-label")}}
	{% if form.email.errors %}
{{form.username(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.email.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.email(class="form-control form-control-lg")}}
{%endif%}



</div>





</div>
<div class="form-group">
	



</div>
<div class="form-group">
	{{form.picture.label()}}
	{{form.picture(class="form-control-file")}}
	{%  if form.picture.errors %}
	{% for error in form.picture.errors %}
	<span class="text-danger"> {{error}} </span> 
	 </br>
{% endfor %}
	{% endif %}

	</div>

</fieldset>

<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

   </form>
</div>
	</div>
	</div>

{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
   

market/templates/create_post.html
{% extends "layout.html" %}
     {%block content%}
     
     <div class="content-section">
     	<form method="POST" action="">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > {{legend}}</legend>


<div class="form-group">
	{{form.title.label(class="form-control-label")}}
	{% if form.title.errors %}
{{form.title(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.title.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.title(class="form-control form-control-lg")}}
{%endif%}



</div>

<div class="form-group">
	{{form.content.label(class="form-control-label")}}
	{% if form.content.errors %}
{{form.content(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.content.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.content(class="form-control form-control-lg")}}
{%endif%}









</fieldset>
<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

	<small class="text-muted ml-2"> <a href="#"> </a> </small>

   </form>

   <div class="border-top pt-3">

   
    {% endblock %}

   

market/templates/home.html
{% extends "layout.html" %}
     {%block content%}
     
    <h1> Home page</h1>

   
    {% endblock %}

   

market/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='main.css')  }}">

    <title>Home Page</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Flask Market</a>
 
  <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
        <a class="nav-link"href="{{url_for('main.home')}}">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.market_page')}}">Market</a>
    </li>
</ul>
<ul class="navbar-nav">
{% if current_user.is_authenticated %}
<a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
 <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
 <a class="nav-link" href="{{url_for('users.account')}}">account</a>
{% else %}

    <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
    </li>

</ul>
{% endif %}
  </div>

</nav>
    {%   with messages=get_flashed_messages(with_categories=true)  %}
    {% if messages %}
    {% for category,message in messages%}


    {%endfor%}
    <div class="alert alert-{{category}}">
{{message}}

    </div>


    {%endif%}


    {%  endwith %}
    {% block content %} {% endblock%}

    <!-- Optional JavaScript; choose one of the two! -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
<style>
    body{
    background-color: #212121;
    color:white;
    }
</style>
</html>

market/templates/login.html
{% extends "layout.html" %}
     {%block content%}
     <div class="content-section">
     	<form method="POST" action="">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > Log in</legend>


<div class="form-group">
	{{form.email.label(class="form-control-label")}}
	{% if form.email.errors %}
{{form.email(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.email.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.email(class="form-control form-control-lg")}}
{%endif%}



</div>

<div class="form-group">
	{{form.password.label(class="form-control-label")}}
	{% if form.password.errors %}
{{form.password(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.password.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.password(class="form-control form-control-lg")}}
{%endif%}








</div>
<div class="form-check">
	{{form.remember(class="form-check-input")}}
	{{form.remember.label(class="form-check-label")}}
	
	



</div>

</fieldset>
<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

	<small class="text-muted ml-2"> <a href="{{ url_for('users.reset_request')}}"> Forgot Password ? </a> </small>

   </form>

   <div class="border-top pt-3">
   	<small class="text-muted"> 
   		Register <a class="ml-2 " href="{{url_for('users.register')}}"> Sign Up</a>
   	</small>
   </div>

   </div>
    {% endblock %}

   

market/templates/market.html
{% extends "layout.html" %}
{% block content %}
  <table class="table table-hover table-dark">
    <thead>
        <tr>
            <!-- Your Columns HERE -->
               <th scope="col">Author </th>
              <th scope="col">Title</th>
               <th scope="col">Content</th>
            
               <th scope="col"> Date  </th>
              <th scope="col"> </th>
    </thead>
    <tbody>
        <!-- Your rows inside the table HERE: -->
        {% for item in items.items %}
        <tr>
                <td>  <a class="mr-2" href="{{url_for('users.user_posts',username=item.author.username)}}"> {{item.author.username}}  </a>   </td>            
                <td> <a class="mr-2" href="{{url_for('posts.post',post_id=item.id)}}"> {{item.title}} </a> </td>
                <td>{{item.content}}</td>
                <td> {{item.date_posted.strftime('%Y-%m-%d')}} </td>
                <td> <img style="width:20px;border-radius:2px;" src="{{  url_for('static',filename='profile_pics/'+ item.author.image_file) }}" > </td>


               
                
            </tr>
        {% endfor %}
       

    </tbody>


</table>
 {% for page_num in items.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {%if page_num %}
        {%if items.page==page_num %}

        <a class="btn btn-info mb-4" href="{{url_for('main.market_page',page=page_num)}}">{{page_num}} </a>
        {% else %}
 <a class="btn btn-outline-info mb-4" href="{{url_for('main.market_page',page=page_num)}}">{{page_num}} </a>
        {%endif%}
        {%else%}




        {%endif%}






        {%endfor%}
{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
   

market/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <table class="table table-hover table-dark">
    <thead>
     
        <tr>
            <!-- Your Columns HERE -->
            <th scope="col">Title</th>
             <th scope="col">Content</th>
             <th scope="col">Author </th>
             <th scope="col"> Date  </th>
              {% if post.author==current_user %}
             <th scope="col"> </th>
               {% endif %}...
            
    <tbody>
        <!-- Your rows inside the table HERE: -->
    
        <tr>
                
                  
                <td> {{post.title}}</td>
                <td>{{post.content}}</td>
                <td> {{post.author.username}} </td> 
                <td> {{post.date_posted.strftime('%Y-%m-%d')}} </td>
                {% if post.author==current_user %}
                <td> <a class="btn btn-secondary btn-sm m-1" href="{{url_for('posts.update_post',post_id=post.id)}}"> Update </a> <button data-toggle="modal" data-target="#exampleModalCenter"

                type="button" class="btn btn-danger btn-sm m-1">  Delete </button>      </td>
                {% endif %}

                


               
                
            </tr>
    

    </tbody>


</table>
<!-- Modal -->
<!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Delete Post</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
     
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
<input class=" btn btn-danger"  type="submit" value="Delete" >
       </form> 
      </div>
    </div>
  </div>
</div>
{% endblock %}

market/templates/register.html
{% extends "layout.html" %}
     {%block content%}
     <div class="content-section">
     	<form method="POST" action="">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > Join Today </legend>
<div class="form-group">
	{{form.username.label(class="form-control-label")}}

	{% if form.username.errors %}
{{form.username(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.username.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.username(class="form-control form-control-lg")}}
{%endif%}

	
	
	


</div>

<div class="form-group">
	{{form.email.label(class="form-control-label")}}
	{% if form.email.errors %}
{{form.username(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.email.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.email(class="form-control form-control-lg")}}
{%endif%}



</div>

<div class="form-group">
	{{form.password.label(class="form-control-label")}}
	{% if form.password.errors %}
{{form.password(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.password.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.password(class="form-control form-control-lg")}}
{%endif%}



</div>
<div class="form-group">
	{{form.confirm_password.label(class="form-control-label")}}
{% if form.confirm_password.errors %}
{{form.confirm_password(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.confirm_password.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.confirm_password(class="form-control form-control-lg")}}
{%endif%}



</div>
<div class="form-group">
	



</div>

</fieldset>
<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

   </form>
</div>
   <div class="border-top pt-3">
   	<small class="text-muted"> 
   		Already Have An Account <a class="ml-2 " href="{{url_for('users.login')}}"> sign in</a>
   	</small>
   </div>

   </div>
    {% endblock %}

   

market/templates/reset_request.html
{% extends "layout.html" %}
     {%block content%}
     <div class="content-section">
     	<form method="POST" action="">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > Reset Password </legend>


<div class="form-group">
	{{form.email.label(class="form-control-label")}}
	{% if form.email.errors %}
{{form.email(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.email.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.email(class="form-control form-control-lg")}}
{%endif%}

</fieldset>
<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

	<small class="text-muted ml-2"> <a href="#"> </a> </small>

   </form>



   </div>
    {% endblock %}

   

market/templates/reset_token.html
{% extends "layout.html" %}
     {%block content%}
     <div class="content-section">
     	<form method="POST" action="">
 {{form.hidden_tag()}}

<fieldset class="form-group"> 

<legend class="border-bottom mb-4" > Reset Password </legend>


<div class="form-group">
	{{form.password.label(class="form-control-label")}}
	{% if form.password.errors %}
{{form.password(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.password.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.password(class="form-control form-control-lg")}}
{%endif%}

<div class="form-group">
  {{form.confirm_password.label(class="form-control-label")}}
  {% if form.confirm_password.errors %}
{{form.confirm_password(class="form-control form-control-lg is-invalid")}}
<div class="invalid-feedback"> 
{% for error in form.confirm_password.errors %}
<span> {{ error }}</span>

{%endfor%}



 </div>
 {% else %}
 {{form.confirm_password(class="form-control form-control-lg")}}
{%endif%}

</fieldset>
<div class="form-group">
	{{form.submit(class="btn btn-outline-info")}}

	</div>

	<small class="text-muted ml-2"> <a href="#"> </a> </small>

   </form>



   </div>
    {% endblock %}

   

market/templates/test.html
<!DOCTYPE html>
<html>
<head>
	
</head>
<body>

		<form method="POST" action="">
		 {{form.hidden_tag()}}
	
		{{ form.dega}}
		{{form.lendet}}
		{{form.title}}
		{{form.submit}}
	</form>



<script type="text/javascript">
	

let a=document.getE

</script>
</body>
</html>

market/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Posts by {{user.username}} ({{items.total}}) </h1>
  <table class="table table-hover table-dark">
    <thead>
        <tr>
            <!-- Your Columns HERE -->
            <th scope="col">Title</th>
             <th scope="col">Content</th>
             <th scope="col">Author </th>
             <th scope="col"> Date  </th>
             <th scope="col"> </th>
    </thead>
    <tbody>
        <!-- Your rows inside the table HERE: -->
        {% for item in items.items %}
        <tr>
                <td>   <a class="mr-2" href="{{url_for('users.user_posts',username=item.author.username)}}">{{item.author.username}}  </a>   </td>            
                <td> <a class="mr-2" href="{{url_for('posts.post',post_id=item.id)}}"> {{item.title}} </a> </td>
                <td>{{item.content}}</td>
                <td> {{item.date_posted.strftime('%Y-%m-%d')}} </td>
                <td> <img style="width:20px;border-radius:2px;" src="{{  url_for('static',filename='profile_pics/'+ item.author.image_file) }}" > </td>


               
                
            </tr>
        {% endfor %}
       

    </tbody>


</table>
 {% for page_num in items.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
        {%if page_num %}
        {%if items.page==page_num %}

        <a class="btn btn-info mb-4" href="{{url_for('users.user_posts',username=user.username, page=page_num)}}">{{page_num}} </a>
        {% else %}
 <a class="btn btn-outline-info mb-4" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}} </a>
        {%endif%}
        {%else%}




        {%endif%}






        {%endfor%}
{% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
   